services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - backend
    restart: unless-stopped
    logging:
      driver: local

  backend:
    image: ghcr.io/hyperleda/hyperleda:latest
    environment:
      - CONFIG=configs/prod/config.yaml
      - ADS_TOKEN
    volumes:
      - ./configs:/usr/src/app/configs
    restart: unless-stopped
    logging:
      driver: local

  grafana:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    container_name: grafana
    restart: unless-stopped
    logging:
      driver: local

