services:
  adminapi:
    image: ghcr.io/hyperleda/hyperleda:latest
    entrypoint: ["uv", "run", "main.py", "adminapi"]
    environment:
      - CONFIG=configs/test/adminapi.yaml
      - ADS_TOKEN
    volumes:
      - ./configs:/usr/src/app/configs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: local

  dataapi:
    image: ghcr.io/hyperleda/hyperleda:latest
    entrypoint: ["uv", "run", "main.py", "dataapi"]
    environment:
      - CONFIG=configs/test/dataapi.yaml
      - SERVER_PORT=8081
    volumes:
      - ./configs:/usr/src/app/configs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: local

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      adminapi:
        condition: service_healthy
      dataapi:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    logging:
      driver: local

