version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      - backend
  backend:
    image: ghcr.io/hyperleda/hyperleda:latest
    environment:
      - CONFIG=configs/prod/config.yaml
    volumes:
      - ./../configs:/usr/src/app/configs
