services:
  hyperledadb:
    image: postgis/postgis:17-3.5
    environment:
      POSTGRES_DB: "hyperleda"
      POSTGRES_USER: "hyperleda"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - hyperleda-network
    healthcheck:
      test: psql 'host=localhost port=5432 dbname=hyperleda user=hyperleda password=$${POSTGRES_PASSWORD}' -qtA -c 'select 1;' || exit 1
      timeout: 5s
      interval: 5s
      retries: 5

  migrate:
    build:
      dockerfile: postgres/dockerfile
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
    entrypoint: /bin/sh -c "cd database/postgres && pgmigrate -c \"postgresql://hyperledadb:5432/hyperleda?user=hyperleda&password=$${POSTGRES_PASSWORD}\" -t latest migrate"
    volumes:
      - .:/database
    depends_on:
      hyperledadb:
        condition: service_healthy
    networks:
      - hyperleda-network

  wait-for-migrate:
    image: busybox
    depends_on:
      migrate:
        condition: service_completed_successfully
    entrypoint: /bin/sh -c "echo 'Migration completed successfully'"
    networks:
      - hyperleda-network

  adminapi:
    image: ghcr.io/hyperleda/hyperleda:latest
    entrypoint: ["uv", "run", "main.py", "adminapi"]
    environment:
      - CONFIG=configs/adminapi.yaml
      - CLIENTS_ADS_TOKEN
      - STORAGE_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - ./configs:/usr/src/app/configs
    restart: unless-stopped
    networks:
      - hyperleda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      - wait-for-migrate
    logging:
      driver: local

  dataapi:
    image: ghcr.io/hyperleda/hyperleda:latest
    entrypoint: ["uv", "run", "main.py", "dataapi"]
    environment:
      - CONFIG=configs/dataapi.yaml
      - STORAGE_PASSWORD=${POSTGRES_PASSWORD:-password}
    volumes:
      - ./configs:/usr/src/app/configs
    restart: unless-stopped
    networks:
      - hyperleda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    depends_on:
      wait-for-migrate:
        condition: service_completed_successfully

  webapp:
    image: ghcr.io/hyperleda/hyperleda-webapp:latest
    networks:
      - hyperleda-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  nginx:
    image: nginx:latest
    volumes:
      - ./configs/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    depends_on:
      adminapi:
        condition: service_healthy
      dataapi:
        condition: service_healthy
      webapp:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - hyperleda-network
      - proxynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/ping"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: local
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`leda.sao.ru`)"
      - "traefik.http.routers.nginx.entrypoints=https"
      - "traefik.http.services.nginx.loadbalancer.server.port=80"
      - "traefik.docker.network=proxynet"

networks:
  hyperleda-network:
    driver: bridge
  proxynet:
    external: true