server:
  host: 0.0.0.0
  port: 8080
  path_prefix: /admin/api

auth_enabled: false

storage:
  endpoint: localhost
  # endpoint: host.docker.internal # if inside a docker container
  port: 6432
  dbname: hyperleda
  user: hyperleda
  password: password

clients:
  ads_token: token
