server:
  host: http://localhost
  port: 8000
  auth_enabled: true

storage:
  endpoint: localhost
  port: 6432
  dbname: hyperleda
  user: hyperleda
  password: password

queue:
  endpoint: localhost
  port: 6379
  queue_name: default
