server:
  host: http://localhost
  port: 8000

storage:
  endpoint: localhost
  port: 5432
  dbname: hyperleda
  user: hyperleda
  password: password

queue:
  endpoint: localhost
  port: 6379
  queue_name: default
