server:
  host: 0.0.0.0
  port: 8080

storage:
  endpoint: dm2.sao.ru
  port: 5432
  dbname: hyperleda
  user: hyperleda
  password: fake

catalogs:
  velocity:
    apexes:
      heliocentric:
        lon: 0
        lat: 0
        vel: 0
      local_group:
        lon: 93
        lat: -4
        vel: 316
