server:
  host: 0.0.0.0
  port: 8080

storage:
  endpoint: dm2.sao.ru
  port: 5432
  dbname: hyperleda
  user: hyperleda
  password: fake

catalogs:
  velocity:
    apexes:
      heliocentric:
        lon: 
          value: 0
          error: 0
        lat: 
          value: 0
          error: 0
        vel: 
          value: 0
          error: 0
      local_group:
        lon:
          value: 93
          error: 2
        lat:
          value: -4
          error: 2
        vel: 
          value: 316
          error: 5
