/* pgmigrate-encoding: utf-8 */

-- Drop foreign key constraints that reference rawdata.objects or rawdata.tables
-- Note: Constraint names are auto-generated by PostgreSQL, so we find and drop them dynamically
DO $$
DECLARE
    r RECORD;
BEGIN
    -- Find and drop all foreign keys that reference rawdata.objects or rawdata.tables
    FOR r IN (
        SELECT tc.table_schema, tc.table_name, tc.constraint_name
        FROM information_schema.table_constraints tc
        JOIN information_schema.referential_constraints rc 
            ON tc.constraint_name = rc.constraint_name 
            AND tc.table_schema = rc.constraint_schema
        JOIN information_schema.constraint_column_usage ccu 
            ON rc.unique_constraint_name = ccu.constraint_name
            AND rc.unique_constraint_schema = ccu.constraint_schema
        WHERE tc.constraint_type = 'FOREIGN KEY'
          AND ccu.table_schema = 'rawdata'
          AND ccu.table_name IN ('objects', 'tables', 'crossmatch')
    ) LOOP
        EXECUTE format('ALTER TABLE %I.%I DROP CONSTRAINT IF EXISTS %I', 
            r.table_schema, r.table_name, r.constraint_name);
    END LOOP;
END $$;

DROP TRIGGER IF EXISTS set_modification_time_on_pgc_update ON rawdata.objects;

ALTER TABLE rawdata.tables SET SCHEMA layer0;
ALTER TABLE rawdata.objects SET SCHEMA layer0;

ALTER TYPE rawdata.crossmatch_status SET SCHEMA layer0;

ALTER TABLE rawdata.crossmatch SET SCHEMA layer0;

ALTER TABLE layer0.crossmatch 
ADD FOREIGN KEY (object_id) REFERENCES layer0.objects(id);

ALTER TABLE icrs.data 
ADD FOREIGN KEY (object_id) REFERENCES layer0.objects(id);

ALTER TABLE designation.data 
ADD FOREIGN KEY (object_id) REFERENCES layer0.objects(id);

ALTER TABLE cz.data 
ADD FOREIGN KEY (object_id) REFERENCES layer0.objects(id) ON DELETE restrict ON UPDATE cascade;

ALTER TABLE layer0.column_modifiers 
ADD FOREIGN KEY (table_id) REFERENCES layer0.tables(id);

CREATE TRIGGER set_modification_time_on_pgc_update
BEFORE UPDATE OF pgc ON layer0.objects
FOR EACH ROW
EXECUTE FUNCTION rawdata_set_modification_time();

