DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'db_reader') THEN
        CREATE ROLE my_new_role;
    END IF;
END
$$;
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'db_writer') THEN
        CREATE ROLE my_new_role;
    END IF;
END
$$;

ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA cz GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA designation GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA icrs GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA layer0 GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA layer2 GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA nature GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA photometry GRANT SELECT ON TABLES TO db_reader;
ALTER DEFAULT PRIVILEGES IN SCHEMA rawdata GRANT SELECT ON TABLES TO db_reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA common GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA cz GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA designation GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA icrs GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA layer0 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA layer2 GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA nature GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA photometry GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
ALTER DEFAULT PRIVILEGES IN SCHEMA rawdata GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO db_writer;
