name: Build documentation
on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.10' 
        - name: Install dependencies
          run: |
            pip install -r requirements.txt
        - name: Set github-actions permissions
          run: |
            git config user.name 'github-actions[bot]' && git config user.email 'github-actions[bot]@users.noreply.github.com'
        - name: Deploy docs
          run: |
            make deploy-docs
