name: Infra testing

on:
  - push

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Generate SSH key pair for testing
        run: |
          ssh-keygen -t rsa -b 4096 -f /tmp/test_key -N "" -C "test@github.com"
          chmod 600 /tmp/test_key
          chmod 644 /tmp/test_key.pub

      - name: Start server container
        run: |
          docker run -d \
            --name test-container \
            --network host \
            -v /tmp:/tmp \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e PUID=1000 \
            -e PGID=1000 \
            -e USER_NAME=tester \
            -e SUDO_ACCESS=true \
            -e PASSWORD_ACCESS=true \
            -e USER_PASSWORD=password \
            linuxserver/openssh-server:latest

      - name: Setup add key to server
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-copy-id -f -i /tmp/test_key.pub localhost

      - name: Deploy
        run: |
          uv run python infra/deploy.py infra/configs/dev.yaml

      - name: Test endpoint
        run: |
          ssh -o StrictHostKeyChecking=no -i /tmp/test_key tester@localhost "curl -f http://localhost:80/ping"
