name: Infra testing

on:
  - push

jobs:
  test-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install project dependencies
        run: uv sync --all-extras --dev

      - name: Start server container
        run: |
          docker run -d \
            --name test-container \
            --network host \
            -v /tmp:/tmp \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -e PUID=1000 \
            -e PGID=1000 \
            -e USER_NAME=tester \
            -e SUDO_ACCESS=true \
            -e PASSWORD_ACCESS=true \
            -e USER_PASSWORD=password \
            linuxserver/openssh-server:latest

      - name: Setup client
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          ssh-keyscan -H localhost >> ~/.ssh/known_hosts

      - name: Deploy
        run: |
          uv run python infra/deploy.py infra/configs/dev.yaml

      - name: Test endpoint
        run: |
          sshpass -p password ssh -o StrictHostKeyChecking=no tester@localhost "curl -f http://localhost:80/ping"
