name: Regression testing
on:
  - push

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Start environment
        run: |
          docker compose up -d

      - name: Start AdminAPI server
        env:
          ADS_TOKEN: ${{ secrets.ADS_TOKEN }}
        run: |
          make adminapi &

      - name: Run tests
        run: |
          make test-regression
