server:
  host: 0.0.0.0
  port: 8080

auth_enabled: false

storage:
  endpoint: 172.17.0.1
  port: 6432
  dbname: hyperleda
  user: hyperleda
  password: password

queue:
  endpoint: 172.17.0.1
  port: 6379
  queue_name: default
